/*WAQTD ENAME,DNAME OF EMPLOYEE
JOINS:
"IT IS PROCESS OF RETRIVING DATA FROM
MULTIPLE TABLES SIMULTANESOULY
 IS KNOWN AS JOINS"
 THERE ARE 5 TYPES OF JOINS
 1)CARTESIAN JOIN/CROSS JOIN
 2)INNER JOIN/EQUI JOIN
 3)OUTER JOIN
   ->LEFT OUTER JOIN
   ->RIGHT OUTER JOIN
   ->FULL OUTER JOIN
4)SELF JOIN
5)NATURAL JOIN
1)CARTESIAN JOIN/CROSS JOIN:
"IN CARTESIAN JOIN TABLE1 RECORDS ARE
MERGED WITH ALL THE RECORDS OF TABLE2"
SYNTAX:ANSI
SELECT COLUMN_NAME1,COLUMN_NAME2,.....
FROM TABLE_NAME1 CROSS JOIN TABLE_NAME2;
*/
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT ENAME,DNAME
FROM EMP CROSS JOIN DEPT;
/* INNER JOIN/EQUI JOIN:
"IT IS USED TO OBTAIN ONLY MATCHING RECORDS
OR RECORDS WHICH HAS PAIR".
JOIN CONDITION:
"IT IS CONDITION ON WHICH TWO TABLES
ARE MERGED OR JOINED".
SYNTAX:JOIN CONDITION
TABLE_NAME1.COLUMN_NAME=TABLE_NAME2.COLUMN_NAME;
EX:EMP.DEPTNO=DEPT.DEPTNO

SYNTAX:INNER JOIN
SELECT COLUMN_NAME1,COLUMN_NAME2....
FROM tabl_NAME1 INNER JOIN TABLE_NAME2
ON <JOIN CONDITION>;*/
SELECT ENAME,DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO;
/*WAQTD ENAME,SALARY,DNAME OF EMPLOYEE.*/
SELECT ENAME,SAL,DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO;
/*WAQTD ENAME,JOB,LOCATION OF EMPLOYEE
IF EMPLOYEE IS WORKING AS ANALYST*/
SELECT ENAME,JOB,LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE JOB='ANALYST';
/*WAQTD ENAME,SAL,DNAME,LOC OF EMPLOYEE
IF EMPLOYEE WORKING AS MANAGER OR CLERK
IN DEPTNO 10 OR 20.*/
SELECT ENAME,SAL,DNAME,LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE JOB IN('MANAGER','CLERK')
AND EMP.DEPTNO IN(10,20);
/*WAQTD NAME,JOB HIREDATE OF EMPLOYEE
 IF EMPLOYEE WORKING IN A LOCATION
NEW YORK OR DALLAS*/
SELECT ENAME,JOB,HIREDATE,LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE LOC IN('NEW YORK','DALLAS');
/*WAQTD EMPNO,ENAME,COMM,DNAME OF EMPLOYEE
 IF EMPLOYEE IS GETTING SALARY
 MORE THAN BLAKE &WORKING IN DNAME 
 RESEARCH OR SALES*/
SELECT EMPNO,ENAME,COMM,DNAME,COMM
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE SAL>(SELECT SAL
           FROM EMP
		   WHERE ENAME='BLAKE') AND 
DNAME IN('RESEARCH','SALES');
/*WAQTD ENAME,DNAME,LOC,HIREDATE,JOB
OF EMPLOYEE ALONG WITH THEIR DEPTNO 
IF EMPLOYEE NAME LAST BUT ONE CHARACTER IS
R AND GETTING SALARY IN THE RANGE OF
1000 AND 5000 OR EMPLOYEE HIRED AFTER
1980 OR EMPLOYEE IS HIRED BEFORE MILLER AND
EMPLOYEE IS NOT GETTING COMMISSION OR EMPLOYEE IS
WORKING AS MANAGER OR SALESMAN OR ANALYST.*/
SELECT ENAME,HIREDATE,LOC,JOB,DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE ENAME LIKE '%R_' AND SAL BETWEEN 1000 AND 5000
AND HIREDATE>'1980-12-31' OR HIREDATE<(SELECT HIREDATE
                                        FROM EMP
                                        WHERE ENAME='MILLER')
AND COMM IS NULL OR JOB IN('MANAGER','SALESMAN','ANALYST');
/*WAQTD EMPLOYEE NAME &MANAGER'SNAME OF EMPLOYEE*/
/*SELF JOIN
"JOINING THE TABLE BY ITSELF IS KNOWN AS SELF JOIN
WHY???
WHENEVER DATA TO BE SELECTED FROM SAME TABLE
BUT PRESENT IN DIFFRENT RECORDS WE USE SELF JOIN.
SYNTAX:
SELECT COLUMN_NAME1,COLUMN_NAME2......
FROM TABLE_NAME T1 JOIN TABLE_NAME T2
ON <JOIN CONDITION>; */
SELECT E1.ENAME,E1.SAL,M1.ENAME AS MANAGER
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO;
/*WAQTD EMPLOYEE NAME,EMPLOYEE SALARY MANAGER'S NAME,
 MANAGER'S SALARY OF EMPLOYEE*/
SELECT E1.ENAME,E1.SAL,M1.ENAME,M1.SAL
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO;
/*WAQTD EMPLOYEE NAME,EMPLOYEE JOB ,MANAGER'S NAME,MANAGER'S JOB
OF EMPLOYEE*/
SELECT E1.ENAME,E1.JOB,M1.ENAME,M1.JOB
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO;

SELECT * FROM EMP;
/*WAQTD EMPLOYEE NAME, EMPLOYEE SALARY ,MANAGER'NAME
MANAGER'S SALARY OF EMPLOYEE IF MANAGER IS GETTING
SALARY LESS THAN EMPLOYEE*/
SELECT E1.ENAME,E1.SAL,M1.ENAME,M1.SAL
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO
WHERE M1.SAL<E1.SAL;
/*WAQTD EMPLOYEE NAME,EMPLOYEE JOB ,MANAGER'S ENAME&
MANAGER'S JOB IF MANAGER IS WORKING AS ANALYST*/
SELECT E1.ENAME,E1.JOB,M1.ENAME,M1.JOB
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO
WHERE M1.JOB='ANALYST';

/*WAQTD EMPLOYEE NAME,EMPLOYEE SALARY,MANAGER'SNAME
MANAGER'S SALARY ,MANAGER'S MANAGER NAME,MANAGER'S MANAGER
SALARY OF EMPLOYEE*/
SELECT E1.ENAME,E1.SAL,M1.ENAME,M1.SAL,M2.ENAME,M2.SAL
FROM EMP E1 JOIN EMP M1 JOIN EMP M2
ON E1.MGR=M1.EMPNO AND M1.MGR=M2.EMPNO;



