USE EXCELR01;


/*QUESTION-01*/
SELECT ENAME,COMM FROM EMP
WHERE COMM IS NULL;

/*QUESTION-02*/
SELECT ENAME, MGR FROM EMP
WHERE MGR IS NULL;

/*QUESTION-03*/
SELECT ENAME,DEPTNO,JOB FROM EMP
WHERE DEPTNO=30 AND JOB="SALESMAN";

/*QUESTION-04*/
SELECT ENAME,JOB,DEPTNO,SAL FROM EMP
WHERE DEPTNO=30 AND JOB="SALESMAN" AND SAL=1500;

/*QUESTION-05*/
SELECT ENAME FROM EMP
WHERE ENAME LIKE "S%" OR ENAME LIKE"A%";

/*QUESTION-06*/
SELECT ENAME,DEPTNO FROM EMP
WHERE DEPTNO != 10 AND DEPTNO != 20;

/*QUESTION-07*/
SELECT ENAME FROM EMP
WHERE ENAME NOT LIKE "S%";

/*QUESTION-08*/
SELECT ENAME, MGR, DEPTNO FROM EMP
WHERE DEPTNO=10 AND MGR IS NOT NULL;

/*QUESTION-09*/
SELECT ENAME, JOB,COMM FROM EMP
WHERE JOB="CLERK" AND COMM IS NULL;

/*QUESTION-10*/
SELECT * from emp
WHERE mgr IS NULL
AND deptno NOT IN (10, 30);

/*QUESTION-11*/
select ename, job, sal,deptno from emp
where deptno=30 and sal >2450;

/*QUESTION-12*/
select ename, job, deptno from emp
where deptno=20 and sal > 2500 and job="analyst";

/*QUESTION-13*/
select ename from emp
where ename like "M%" OR ENAME LIKE"J%";

/*QUESTION-14*/
SELECT ENAME,DEPTNO, SAL *12 AS ANNUAL_SAL FROM EMP
WHERE DEPTNO !=30;

/*QUESTION-15*/
SELECT ENAME FROM EMP
WHERE ENAME NOT LIKE "%E" AND ENAME NOT LIKE "%S" AND ENAME NOT LIKE "%R";

/*QUESTION-16*/
SELECT ENAME,MGR,DEPTNO,SAL*1.1 FROM EMP
WHERE DEPTNO=10 AND SAL *1.1  ;

/*QUESTION-17*/
SELECT ENAME,JOB FROM EMP
WHERE job="salesman" and ENAME LIKE"%E_";

/*QUESTION-18*/
SELECT ENAME, HIREDATE FROM EMP
WHERE HIREDATE > "1981-12-31";

/*QUESTION-19*/
SELECT ENAME , HIREDATE FROM EMP
WHERE HIREDATE BETWEEN "1981-01-01" AND "1981-12-31";

/*QUESTION-20*/
SELECT ENAME,JOB,DEPTNO,SAL FROM EMP
WHERE JOB NOT IN ("MANAGER","CLERK")
AND DEPTNO NOT IN (10,20)
AND SAL BETWEEN 1000 AND 3000;