USE EXCELR01;

#1.WAQTD NAME OF THE EMPLOYEE AND HIS MANAGERS NAME IF EMPLOYEE IS WORKING AS CLERK.

SELECT E1.ENAME,E1.JOB,M1.ENAME
FROM EMP E1 JOIN EMP M1
ON E1.MGR = M1.EMPNO
WHERE M1.JOB="CLERK";

#2.WAQTD NAME OF THE EMPLOYEE AND MANAGERS DESIGNATION IF MANAGER WORKS IN DEPT 10 OR 20. 

SELECT E1.ENAME, E1.JOB,E1.DEPTNO, M1.ENAME
FROM EMP E1 JOIN EMP M1
ON E1.MGR = M1.EMPNO
WHERE M1.DEPTNO IN (10,20);

#3.WAQTD NAME OF THE EMP AND MANAGERS SALARY IF EMPLOYEE AND MANAGER BOTH EARN MORE THAN 2300.

SELECT E1.ENAME, E1.SAL AS EMP_SAL, M1.SAL AS MGR_SAL
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO
WHERE E1.SAL > 2300 AND M1.SAL >2300;

#4.WAQTD EMP NAME AND MANAGERS HIREDATE IF EMPLOYEE WAS HIRED BEFORE 1982

SELECT E1.ENAME, E1.HIREDATE AS EMP_HIREDATE, M1.ENAME AS MGR_NAME, M1.HIREDATE AS MGR_HIREDATE
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO
WHERE E1.HIREDATE < "1982-01-01";

#5.WAQTD EMP NAME AND MANAGERS COMM IF EMPLOYEE WORKS AS SALESMAN AND MANAGER WORKS IN DEPT 30 

SELECT E1.ENAME, E1.JOB, M1.ENAME,M1.COMM, M1.DEPTNO
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO
WHERE E1.JOB="SALESMAN" AND M1.DEPTNO=30;

#6.WAQTD EMP NAME AND MANAGER NAME AND THEIR SALARIES IF EMPLOYEE EARNS MORE THAN MANAGER

SELECT E1.ENAME, E1.SAL AS EMP_SAL, M1.ENAME,M1.SAL AS MGR_SAL
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO
WHERE E1.SAL > M1.SAL;

#7.WAQTD EMP NAME AND HIREDATE , MANAGER NAME AND HIREDATE IF MANAGER WAS HIRED BEFORE EMPLOYEE

SELECT E1.ENAME, E1.HIREDATE AS EMP_HIRE, M1.ENAME, M1.HIREDATE AS MGR_HIRE
FROM EMP E1 JOIN EMP M1
ON E1.MGR= M1.EMPNO
WHERE M1.HIREDATE > E1.HIREDATE;

#8.WAQTD EMP NAME AND MANAGER NAME IF BOTH ARE WORKING IN SAME JOB.

SELECT E1.ENAME, E1.JOB AS EMP_JOB, M1.ENAME, M1.JOB AS MGR_JOB
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO
WHERE E1.JOB=M1.JOB;

#9.WAQTD EMP NAME AND MANAGER NAME IF MANAGER IS WORKING AS ACTUAL MANAGER

SELECT E1.ENAME AS EMP_NAME, M1.ENAME AS MGR_NAME
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO
WHERE M1.JOB="MANAGER";

#10.WAQTD EMP NAME AND MANAGER NAME ALONG WITH THEIR ANNUAL SALARIES IF EMPLOYEE WORKS IN DEPT 10 , 20 AND MANAGERS SAL IS GREATER THAN EMPLOYEES SALARY.

SELECT E1.ENAME, (E1.SAL * 12) AS EMP_SAL, M1.ENAME, (M1.SAL*12) AS MGR_SAL
FROM EMP E1 JOIN EMP M1
ON E1.MGR= M1.EMPNO
WHERE E1.DEPTNO IN(10,20) AND M1.SAL > E1.SAL;

#11.WAQTD EMPLOYEE'S NAME AND MANAGER'S DESIGNATION FOR ALL THE EMPLOYEES

SELECT E1.ENAME, M1.ENAME AS MGR_DESIGNATION
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO;

#12.WAQTD EMPLOYEES NAME AND MANAGERS SALARY FOR ALL THE EMPLOYEES IF MANAGER'S SALARY ENDS

SELECT E1.ENAME, M1.ENAME, M1.SAL AS MGR_SAL
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO
WHERE M1.SAL LIKE "%0";

