use excelr01;

#1)	WAQTD ename , sal and dname of the employee working as Clerk in dept 20 with a salary of more than 1800 .

SELECT ENAME,SAL,DNAME FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE JOB="CLERK" AND SAL > 1800
AND DEPTNO=20;

#2)	WAQTD ename deptno , dname and loc of the employee earning more than 2000 in New York .

SELECT ENAME,DEPTNO,DNAME,LOC FROM EMP
INNER JOIN DEPT

WHERE SAL>2000 AND LOC="NEW YORK";

#3)	NAME OF THE EMPLOYEE AND HIS LOCATION OF ALL THE EMPLOYEES .

SELECT ENAME, LOC FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO;

#4)	WAQTD DNAME AND SALARY FOR ALL THE EMPLOYEE WORKING IN ACCOUNTING.

SELECT DNAME,SAL FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE DNAME="ACCOUNTING";

#5)	WAQTD DNAME AND ANNUAL SALARY FOR ALL  EMPLOYEES WHOS SALARY IS MORE THAN 2340

SELECT ENAME,DNAME, SAL*12 AS ANNUAL_SAL FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE SAL > 2340;

#6)	WAQTD ENAME AND DNAME FOR EMPLOYEES HAVING CAHARACTER 'A' IN THEIR DNAME 

SELECT ENAME, DNAME FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE DNAME LIKE "%A%";

#7)	WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES WORKING AS SALESMAN

SELECT ENAME,DNAME FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE JOB="SALESMAN";

#8)WADTD DNAME AND JOB FOR ALL THE EMPLOYEES WHOSE JOB AND DNAME STARTS WITH CHARACTER 'S'

SELECT DNAME, JOB FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE JOB LIKE "S%" AND DNAME LIKE "S%";

#9)WAQTD DNAME AND MGR Number FOR EMPLOYEES REPORTING TO 7839.

SELECT DNAME, MGR FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE MGR=7839;

#10)WAQTD DNAME AND HIREDATE FOR EMPLOYEES HIRED AFTER 81 INTO ACCOUNTING  OR RESEARCH DEPT .

SELECT DNAME, HIREDATE FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE DNAME IN("ACCOUNTING","RESEARCH")
AND HIREDATE > "1981-12-31";

#11)WAQTD ENAME AND DNAME OF THE EMPLOYEES WHO ARE GETTING COMM IN DEPT 10  OR 30.

SELECT ENAME,COMM, DNAME FROM EMP
INNER JOIN DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO IN(10,30)
AND COMM IS NOT NULL;

#12)WAQTD DNAME AND EMPNO FOR ALL THE EMPLOYEES WHO'S   EMPNO ARE  (7839,7902) AND ARE WORKING IN LOC NEW YORK.

SELECT ENAME,DNAME,EMPNO,LOC FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE EMPNO IN(7839,7902)
AND LOC="NEW YORK";
