USE EXCELR01;
CREATE TABLE OLA
(
CUSTOMER_NAME VARCHAR(50),
CONTACT_NUMBER BIGINT,
PICK_UP_LOCATION VARCHAR(50),
DRIVER_NAME VARCHAR(50),
PAYMENT_MODE VARCHAR(100),
OTP INT,
DESTINATION VARCHAR(50),
FARE_PRICE INT
);
DESC OLA;
INSERT INTO OLA VALUES
('BHUSHAN',1234567891,"BANER","OM","ONLINE",
 12344,"SHIVAJI_NAGAR",500);
 SELECT *
 FROM OLA;
 UPDATE OLA
 SET DRIVER_NAME="ASHOTOSH",FARE_PRICE=1000
 WHERE OTP=12344;
 UPDATE OLA
 SET PAYMENT_MODE="CASH"
 WHERE DRIVER_NAME="OM";
 SELECT * FROM AMAZON;
 /*DELETE:
 "IT IS USED TO DELETE THE PARTICULAR 
  RECORD/ROW FROM THE TABLE"
 SYNTAX:
 DELETE FROM TABLE_NAME 
 WHERE <FILTER_CONDITION>;
 */
 DELETE FROM AMAZON 
 WHERE PRODUCT_DESCRIPTION="BEST_PRODUCT";
 SELECT *
 FROM AMAZON;
 
 DELETE FROM AMAZON WHERE ORDER_ID=1;
 
 DELETE FROM AMAZON WHERE PNAME="IPHONE";
 SELECT *
 FROM AMAZON;
INSERT INTO AMAZON VALUES(1,"MOBILE",20000,1,"PP"),
                         (2,"WATCH",35000,2,"QQQ");
SELECT * FROM AMAZON;
DELETE FROM AMAZON ;
 
 
 DELETE FROM AMAZON WHERE QUANTITY=2;
 TRUNCATE TABLE AMAZON;
 SELECT * FROM AMAZON;
 /*CONSTRAINTS:
 "THESE ARE THE RULES GIVEN COLUMN VALIDATION".
 ->THERE ARE 6 TYPES OF CONSTRAINTS.
 1)UNIQUE
 2)NOT NULL
 3)CHECK 
 4)PRIMARY KEY
 5)FOREIGN KEY
 6)DEFAULT
 1)UNIQUE:
 "IT IS USED TO AVOID DUPLICATE/REPETED VALUE
 INTO THE COLUMN".
 2)NOT NULL:
 "IT IS USED TO AVOID NULL VALUE INTO THE
  COLUMN".
3)CHECK:
"IT IS USED FOR EXTRA VALIDATION IF CONDITION
SATISFY IT WILL ACCEPT THE VALUE ELSE
IT WILL REJECT THE VALUE"
4)PRIMARY KEY:
"IT IS USED TO IDENTIFY UNIQUELY RECORDS 
FROM THE TABLE".
CHARACTERISTICS OF PRIMARY KEY.
1)IN A TABLE WE MUST HAVE ONLY 1 PRIMARY KEY.
2)PRIMARY KEY IS ALWAYS A COMBINATION OF
UNIQUE &NOT NULL CONSTRAINT.
3)PRIMARY KEY WILL NOT ACCEPT DUPLICATE/REPETED
  VALUE.
4)PRIMARY KEY WILL NOT ACCEPT NULL VALUE.

FOREIGN KEY:
"IT IS USED TO ESTABLISH RELATION BETWEEN
TWO OR MORE TABLES".
CHARACTERISTICS OF FOREIGN KEY:
1)IN TABLE WE CAN HAVE MULTIPLE COLUMN_NAMES
AS FOREIGN KEY.
2)FOREIGN IS NOT COMBINATION OF UNIQUE&
  NOT NULL CONSTRAINT.
3)FOREIGN KEY WILL ACCEPT DUPLICATE/REPETED
VALUE.
4)FOREIGN KEY WILL ACCEPT NULL VALUE.
5)FOR A COLUMN/ATTRIBUTE WANT TO BECOME 
  FOREIGN KEY IT MUST BE A PRIMARY KEY
  ON ITS OWN TABLE.
6)FOREIGN KEY IS ALSO KNOWN AS REFFRENTIAL
INTIGRITY CONSTRAINT.*/
/*INTERVIEW QUESTION DIFFERENCE BETWEEN PRIMARY KEY & FOREIGN KEY*/
CREATE TABLE CUSTOMER
(
CID INT PRIMARY KEY,
CNAME VARCHAR(50) NOT NULL,
EMAIL_ID VARCHAR(50) UNIQUE NOT NULL,
PHNO BIGINT CHECK(LENGTH(PHNO)=10) UNIQUE NOT NULL
);
INSERT INTO CUSTOMER VALUES(1,"ARUN","ARUN@GMAIL.COM",9874561231);
INSERT INTO CUSTOMER VALUES(2,"BHUSHAN",'B@GMAIL.COM',9874561232);

CREATE TABLE PRODUCT
(
PID INT PRIMARY KEY,
PNAME VARCHAR(50) NOT NULL,
PRICE DECIMAL(10,2),
CID INT,
CONSTRAINT CID_FK FOREIGN KEY(CID) references CUSTOMER(CID)
);
DROP TABLE CUSTOMER;







