USE EXCELR01;
SELECT ENAME,DEPTNO FROM EMP
WHERE DEPTNO=10 OR DEPTNO=20 OR DEPTNO=30 OR DEPTNO=40;

SELECT ENAME,DEPTNO FROM EMP
WHERE DEPTNO IN(10,20,30,40);

SELECT ENAME,JOB FROM EMP
WHERE JOB IN("SALESMAN","ANALYST");

SELECT ENAME, SAL FROM EMP
WHERE SAL IN(800,1000,3000);

SELECT ENAME, JOB FROM EMP
WHERE JOB NOT IN("PRESIDENT","CLERK");

SELECT ENAME , JOB FROM EMP
WHERE JOB != "PRESIDENT" AND JOB!="CLERK";

SELECT ENAME,HIREDATE FROM EMP
WHERE HIREDATE >="1981-01-01"
AND HIREDATE <="1981-12-31";

SELECT ENAME,HIREDATE FROM EMP
WHERE HIREDATE BETWEEN "1981-01-01" AND "1981-12-31";

SELECT ENAME,SAL FROM EMP
WHERE SAL BETWEEN 1500 AND 3000;

SELECT ENAME, HIREDATE FROM EMP
WHERE HIREDATE NOT BETWEEN "1981-01-01" AND "1981-12-31";

SELECT ENAME, SAL FROM EMP
WHERE SAL IS NULL;

SELECT ENAME, COMM FROM EMP
WHERE COMM IS NULL;

SELECT ENAME, SAL FROM EMP
WHERE SAL IS NOT NULL;

SELECT ENAME, MGR FROM EMP
WHERE MGR IS NOT NULL;

SELECT ENAME FROM EMP
WHERE ENAME LIKE "A%";

SELECT ENAME FROM EMP
WHERE ENAME LIKE "%A";

SELECT ENAME FROM EMP
WHERE ENAME LIKE "K%";

SELECT ENAME FROM EMP
WHERE ENAME LIKE "%N";

SELECT ENAME FROM EMP
WHERE ENAME LIKE "S%" AND ENAME LIKE"%T";

SELECT ENAME FROM EMP
WHERE ENAME LIKE "S%T";

SELECT ENAME FROM EMP
WHERE ENAME LIKE "S%%T";

SELECT ENAME FROM EMP
WHERE ENAME LIKE "%A%";

SELECT ENAME FROM EMP
WHERE ENAME LIKE "____";

SELECT ENAME FROM EMP
WHERE ENAME LIKE"_A%";

SELECT ENAME FROM EMP
WHERE ENAME LIKE "__L%";

SELECT ENAME FROM EMP
WHERE ENAME LIKE "K%";

SELECT ENAME FROM EMP /* GENERAL CASE*/
WHERE ENAME LIKE "A%" OR ENAME LIKE"E%" OR ENAME LIKE"I%" OR ENAME LIKE"O%" OR ENAME LIKE "U%";

SELECT ENAME FROM EMP
WHERE ENAME NOT LIKE "A%" AND ENAME NOT LIKE"E%" AND ENAME NOT LIKE"I%" AND ENAME NOT LIKE"O%" AND ENAME  NOT LIKE "U%";

SELECT ENAME FROM EMP
WHERE ENAME LIKE"%@_%" ESCAPE "@";
















