use excelr01;
select *
from emp;
create table product
(
pid int,
pname varchar(50),
price int);
insert into product values(1,'mobile1',10000),
                          (2,'mobile2',20000),
                          (3,'mobile3',25000),
                          (4,'mobile4',50000),
                          (5,'mobile5',70000);
select *
from product;
SELECT PNAME,PRICE,
CASE WHEN PRICE>50000 THEN
"EXPENSIVE PRODUCT"
ELSE
"NOT EXPENSIVE PRODUCT"
END STATUS
FROM PRODUCT;
SELECT ENAME,SAL,
CASE WHEN SAL>2500 THEN
"MAXIMUM SALARIES GIVEN TO EMPLOYEES"
ELSE
"MINIMUM SALARIES GIVEN TO EMPLOYEES"
END  A
FROM EMP;

/*SYNTAX:
SELECT COLUMN_NAME1,COLUMN_NAME2.........,
CASE WHEN <CONDITION> THEN
"DISPLAY MESSAGE"
ELSE
"DISPLAY THE MESSAGE"
END 
FROM TABLE_NAME;
*/
SELECT *
FROM STUDENT;
INSERT INTO STUDENT VALUES(1,'A',65),
                          (2,'B',34),
                          (3,'C',36);
                          
SELECT *,
CASE WHEN SPERCENTAGE>=35 THEN
"PASS"
ELSE
"FAIL"
END STATUS
FROM STUDENT;      

/*FUNCTION
"IT IS BLOCK OF CODE OR LIST OF INSTRUCTIONS WHICH
PERFORM SOME SPECIFIC TASK".
->THERE 3 MAIN COMPONETS OF FUNCTION
1)FUCTION NAME
2)NO OF ARGUMENTS(NO OF INPUTS)
3)RETURN TYPE.                 
FUNCTION GENERALLY CLASSIFIED INTO 2 TYPES
1)USER DEFINED FUNCTION
2)BUILTIN FUNCTION
->BUILTIN FUNCTION IS CATAGORISED INTO 2 TYPES
   1)SINGLE ROW FUNCTION/SCALR FUNCTION
   2)MULTI ROW FUNCTION/AGGREGATE FUNCTION/GROUP FUNCTION
 /*WAQTD MAXIMUM SALARY OF EMPLOYEE*/
 SELECT MAX(SAL)
 FROM EMP;
/*WAQTD MAXIMUM SALARY GIVEN TO SALESMAN*/
SELECT MAX(SAL)
FROM EMP
WHERE JOB="SALESMAN";
/*WAQTD MINIMUM SALARY GIVEN TO EMPLOYEE IF
EMPLOYEE IS WORKING AS MANAGER AND WORKING IN DEPTNO
10 OR 20*/
SELECT MIN(SAL)
FROM emp
WHERE JOB='MANAGER' AND DEPTNO IN(10,20);
/*WAQTD TOTAL SALARY GIVEN TO ANALYST*/
SELECT SUM(SAL)
FROM EMP
WHERE JOB='ANALYST';
/*WAQTD AVERAGE SALARY GIVEN TO EMPLOYEES IF
 EMPLOYEE HAVING REPORTING MANAGER*/
SELECT AVG(SAL)
FROM emp
WHERE MGR IS NOT NULL;
/*WAQTD NUMBER OF EMPLOYEES WORKING AS PRESIDENT*/
SELECT COUNT(*)
FROM EMP
WHERE JOB='PRESIDENT';
/*WAQTD NUMBER OF DEPTNO PRESENT IN EMPLOYEE TABLE*/
SELECT COUNT(DISTINCT DEPTNO)
FROM EMP;
SELECT * FROM EMP;
SELECT COUNT(DISTINCT JOB)
FROM EMP;
/*WAQTD MAXIMUM SALARY,MINIMUM SALARY,TOTAL SALARY,
ANNUALSALARY AND NO OF EMPLOYEE WORKING AS CLERK*/
SELECT MAX(SAL),MIN(SAL),SUM(SAL),COUNT(*),DEPTNO
FROM EMP
WHERE JOB='CLERK';/*ERROR BECAUSE THIS QUERY HAS TO BE
SOLVED WITH GROUP BY CLAUSE*/
/*CHARACTERISTICS OF MULTI-ROW FUNCTION
1)IN MRF()WILL ACCEPT ONLY ONE ARGUMENT COLUMN_NAME/
EXPRESSION.
SELECT MAX(SAL,SAL*12)
FROM EMP;
2)MRF() IGNORES NULL VALUE.
SELECT MIN( )
FROM EMP;
3)MRF() CANNOT BE WRITTEN IN WHERE CLAUSE
4)COUNT IS THE ONLY MRF() WHICH ACCEPTS * AS AN ARGUMENT
5)ALONG WITH MRF() WE CANNOT PASS ANY OTHER COLUMN_NAME
AS AN ARGUMENT*/
/*WAQTD TOTAL SALARY OF EMPLOYEE(SAL+COMM)*/

SELECT ENAME,SAL,COMM,SAL+COMM
FROM EMP;
/*IFNULL:
"IT IS USED ELIMINATE THE SIDE EFFECT USING NULL
IN A ARITHAMATIC OPERATION".
SYNTAX:IFNULL(ARGUMENT1,ARGUMENT2).
ARGUMENT1:HERE WE HAVE TO WRITE COLUMN_NAME/EXPRESSION
         WHICH IS RESULTING NULL VALUE.
ARGUMENT2:HERE WE WRITE NUMERICAL VALUES WHICH WILL
          BE SUBSTITUED IF ARGUMENT1 IS NULL.
*/
SELECT ENAME,SAL,COMM,SAL+COMM,SAL+IFNULL(COMM,0)
FROM EMP;
/*UNION:
IT IS USED TO COMBINE TWO SELECT STATEMENTS &
REMOVE THE DUPLICATE/REPETED VALUE*/
SELECT DEPTNO
FROM EMP
UNION
SELECT DEPTNO
FROM EMP;
/*UNION ALL
"IT IS USED JOIN 2 SELECT STATEMENTS".*/
SELECT SAL
FROM emp
UNION ALL
SELECT SAL
FROM EMP;
/*LENGTH():"IT IS USED TO COUNT NUMBER OF CHARCTERS
PRESENT IN A GIVEN STRING
SYNTAX:LENGTH('STRING')*/
SELECT LENGTH('SHUBHAM');
SELECT NOW();
SELECT SQRT(4);
SELECT PI();
SELECT POW(2,4);