USE EXCELR01;

CREATE TABLE CUSTOMER01
(
CID INT,
CNAME VARCHAR(50),
PID int
);

INSERT INTO CUSTOMER01 VALUES
(1,"VIKAS",1),
(2,"SHUBHAM",5),
(3,"SAEE",8),
(4,"SHIVAM",10);

CREATE TABLE PRODUCT01
(
PID INT,
PNAME VARCHAR(50),
PRICE int
);

INSERT INTO PRODUCT01 VALUES
(1,'MOBILE',25000),
(2,"LAPTOP",35000),
(3,"WATCH",5000),
(5,"MAGGIE",14);


SELECT * FROM PRODUCT01;

SELECT * FROM CUSTOMER01
LEFT JOIN PRODUCT01
ON CUSTOMER01.PID=PRODUCT01.PID;


# SELF JOIN #

SELECT E1.ENAME, M1.ENAME
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO;

# (WAQTD EMPLOYEE NAME, EMPLOYEE SALARY, MANAGER'S NAME,
# MANAGERS SALARY OF EMPLOYEE)

SELECT E1.ENAME, E1.SAL, M1.ENAME AS MANAGER, M1.SAL AS MSAL
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO;

SELECT E1.ENAME, E1.JOB, M1.ENAME, M1.JOB 
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO
WHERE M1.JOB="ANALYST";

SELECT E1.ENAME, E1.SAL, M1.ENAME, M1.SAL
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO
WHERE M1.SAL < E1.SAL;

SELECT E1.ENAME, E1.COMM, M1.ENAME, M1.COMM
FROM EMP E1 JOIN EMP M1
ON E1.MGR=M1.EMPNO
WHERE M1.COMM IS NULL;

SELECT E1.ENAME, E1.SAL, M1.ENAME, M1.SAL, M2.ENAME, M2.SAL
FROM EMP E1 JOIN EMP M1 JOIN EMP M2
ON E1.MGR=M1.EMPNO AND M1.MGR=M2.EMPNO;

# NATURAL JOIN #

SELECT DNAME FROM DEPT
WHERE EXISTS(SELECT DEPTNO FROM EMP
             WHERE EMP.DEPTNO=DEPT.DEPTNO);
			
            
SELECT DNAME FROM DEPT
WHERE NOT EXISTS (SELECT DEPTNO FROM EMP
                  WHERE EMP.DEPTNO=DEPT.DEPTNO);            
             











