USE EXCELR01;
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE IS 
WORKING IN DEPTNO 30*/
/*SELECTION:
"IT IS PROCESS OF RETRIVING DATA BY SELECTING
BOTH ROWS &COLUMNS IS KNOWN AS SELECTION.
SYNTAX:
SELECT * /[DISTINCT]COLUMN_NAME/EXPRESSION[ALIAS]
FROM TABLE_NAME
WHERE <FILTER_CONDITION>;

WHERE CLAUSE:
"IT IS USED TO FILTER THE RECORDS/ROWS"
->WHERE CLAUSE WILL EXECUTE ROW_BY_ROW.
*/
SELECT ENAME,DEPTNO
FROM EMP
WHERE DEPTNO=30;
/*WAQTD NAME&SALARY OF EMPLOYEE IF EMPLOYEE
IS GETTING SALARY MORE THAN 2500*/
SELECT ENAME,SAL
FROM EMP
WHERE SAL>2500;
/*WAQTD NAME &JOB OF EMPLOYEE IF EMPLOYEE
IS WORKING AS MANAGER*/
SELECT *
FROM EMP;
SELECT ENAME,JOB
FROM EMP
WHERE JOB="MANAGER";
/*WAQTD DETAILS OF EMPLOYEE IF EMPLOYEE
  GETTING A COMMISSION RS 1400*/
SELECT *
FROM emp
WHERE COMM=1400;
/*WAQTD NAME&HIREDATE OF EMPLOYEE IF EMPLOYEE
IS HIRED AFTER 1981*/
SELECT ENAME,HIREDATE
FROM emp
WHERE HIREDATE>"1981-12-31";
/*WAQTD NAME &HIREDATE OF EMPLOYEE IF
EMPLOYEE IS HIRED BEFORE 1981*/
SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE<'1981-01-01';
/*WAQTD DEATILS OF EMPLOYEE IF EMPLOYEES
ANNUAL SALARY IS MORE THAN 10000*/
SELECT *
FROM EMP
WHERE SAL*12>10000;
/*WAQTD NAME &JOB OF EMPLOYEE
IF EMPLOYEE IS WORKING IN DEPTNO
20 AND GETTING SALARY MORE THAN 1500*/
/*TYPES OF OPERATORS.
1)ARITHAMATIC OPERATOR(+,-,*,/)
2)CONCATINATION OPERATOR
  "IT IS USED FOR JOINING THE STRINGS
   TOGETHER"
SYNTAX:CONCAT('STRING1','STRING2');
EX: CONCAT('VADA','PAV')->VADAPAV
*/
SELECT CONCAT('VADA'," ",'PAV');
/* 3)COMPARISION OPERATORS(=,!=)
   4)RELATIONAL OPERATORS(<,>,<=,>=)
   5)LOGICAL OPERATORS(AND,OR,NOT)
   6)SPECIAL OPERATORS
   (IN,NOT IN,BETWEEN,NOT BETWEEN,IS,IS NOT,
    LIKE,NOT LIKE)
7)SUBQUERY OPERATOR(ALL,ANY,EXISTS,NOT EXISTS)
/*LOGICAL OPERATORS:
"TO WRITE MULTIPLE CONDITIONS IN WHERE
 CLASUE WE USE LOGICAL OPERATOR.&OUTPUT
 OF LOGICAL OPERATOR IS ALWAYS A BOOLEAN 
 VALUE(TRUE/FALSE).
/*AND:
"IT IS BINARY OPERATOR WHICH ACCEPTS
2 OPRENDS(2 INPUTS).
->AND OPERATOR IS USED WHENVER BOTH OR
ALL THE CONDITIONS MUST BE SATISFIED
*/
SELECT ENAME,JOB,DEPTNO,SAL
FROM EMP
WHERE DEPTNO=20 AND SAL>1500;
/*WAQTD NAME &JOB OF EMPLOYEE IF EMPLOYEE
IS WORKING AS ANALYST AND GETTING SALARY
MORE THAN 2800*/
SELECT ENAME,JOB,SAL
FROM EMP
WHERE JOB="ANALYST" AND SAL>2800;
/*WAQTD NAME&HIREDATE OF EMPLOYEE IF EMPLOYEE
HIRED AFTER 1981 AND BEFORE 1985*/
SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE>'1981-12-31' AND 
HIREDATE<'1985-01-01';
/*WAQTD NAME OF EMPLOYEE IF
  EMPLOYEE IS WORKING IN DEPTNO 10,20,30*/
/*OR:
"IT IS ALSO BINARY OPERATOR WHICH ACCEPTS
 2 OPRENDS(2 INPUTS)
 ->OR OPERATOR IS USED WHENEVER ANY ONE THE
    CONDITION HAS TO BE SATISFIED*/
SELECT ENAME,DEPTNO
FROM EMP
WHERE DEPTNO=10 OR DEPTNO=20 OR DEPTNO=30;
/*WAQTD NAME &JOB&SALARY OF EMPLOYEE
IF EMPLOYEE IS WORKING AS SALESMAN
OR PRESIDENT*/
SELECT ENAME,JOB,SAL
FROM EMP
WHERE JOB='SALESMAN' OR JOB='PRESIDENT';
/*WAQTD DETAILS OF EMPLOYEE IF EMPLOYEE
IS WORKING IN DEPTNO 10 OR 20 AND GETTING
SALARY MORE THAN 1000 AND WORKING AS
ANALYST OR CLERK*/
SELECT *
FROM emp
WHERE (DEPTNO=10 OR DEPTNO=20) AND (SAL>1000)
AND (JOB='ANALYST' OR JOB='CLERK');
/*WAQTD NAME &DEPTNO OF EMPLOYEE IF EMPLOYEE
IS NOT WORKING IN DEPTNO 30*/
SELECT ENAME,DEPTNO
FROM EMP
WHERE NOT DEPTNO=30;
/*WAQTD NAME,HIREDATE,JOB,SAL OF EMPLOYEE
IF EMPLOYEES ANNUAL SALARY MORE THAN 15000
AND WORKING AS SALESMAN OR MANAGER 
OR PRESIDENT AND HIRED AFTER 1982 AND
WORKING IN DEPTNO 20 OR 30 AND NOT WORKING IN DEPTNO 10*/
SELECT ENAME,HIREDATE,JOB,SAL
FROM emp
WHERE SAL*12>15000 AND (JOB="SALESMAN" OR JOB="PRESIDENT" OR
JOB="MANAGER") AND HIREDATE>'1982-12-31' AND
(DEPTNO=20 OR DEPTNO=30) AND DEPTNO!=10;





