use excelr01;
/*SINGLE ROW FUNCTION:
3)UPPER:IT IS USED TO CONVERT LOWERCASE 
LETTERS TO UPPERCASE LETTERS.
SYNTAX:UPPER('STRING')
SELECT UPPER('vikas');
4)LOWER():
"IT IS CONVERT UPPERCASE LETTERS TO 
LOWERCASE LETTERS.
SYNTAX:LOWER('STRING')
EX:SELECT LOWER('ROHITH');
*/
/*WAQTD TO CHECK WHETHER EMPLOYEE NAME IS
PALINDROME OR NOT*/
/*REVERSE:
"IT IS USED TO REVERSE THE GIVEN STRING".
SYNTAX:REVERSE('STRING');
*/
SELECT REVERSE('VIJAY');
SELECT ENAME
FROM emp
WHERE ENAME=REVERSE(ENAME);
UPDATE EMP
SET ENAME='ALLEN'
WHERE ENAME='NITIN';
/*WAQTD EVEN NUMBER EMPLOYEE NUMBER*/
/*MOD():
"IT IS USED TO OBTAIN MODULUS/REMAINDER
OF GIVEN NUMBER"
SYNTAX:MOD(M,N)
*/
SELECT MOD(10,3);
SELECT MOD(10,5);
SELECT EMPNO
FROM EMP
WHERE MOD(EMPNO,2)!=0;
SELECT coalesce('RAHUL',NULL);
CREATE DATABASE SQL124;
USE SQL124;
SET GLOBAL LOG_BIN_TRUST_FUNCTION_CREATORS=1;

/*GROUP BY CLAUSE:
"IT IS USED TO GROUP THE RECORDS"
SYNTAX:
SELECT GROUP FUNCTION/GROUP BY EXPRESSION
FROM TABLE_NAME
[WHERE <FILTER_CONDITION>]
GROUP BY COLUMN_NAME/EXPRESSION;
1)WAQTD NUMBER OF EMPLOYEES WORKING IN EACH
  DEPTNO.
*/
SELECT COUNT(*),DEPTNO
FROM emp
GROUP BY DEPTNO;
/*WAQTD NUMBER OF EMPLOYEES WORKING IN EACH 
DEPTNO EXCEPT ANALYST*/
SELECT COUNT(*),DEPTNO
FROM emp
WHERE JOB!='ANALYST'
GROUP BY DEPTNO;
/*WAQTD MAXIMUM SALARY GIVEN TO EACH JOB*/
SELECT MAX(SAL),JOB
FROM emp
GROUP BY JOB;
/*WAQTD NUMBER OF EMPLOYEES WORKING IN DEPTNO
IF EMPLOYEE NAME HAS CHARACTER A OR S IN THEIR
NAME*/

SELECT COUNT(*),DEPTNO,ENAME
FROM EMP
WHERE ENAME LIKE '%A%' OR ENAME LIKE '%S%'
GROUP BY DEPTNO,ENAME;
/*WAQTD NUMBER OF TIMES SALARY PRESENT IN
 EMPLOYEE TABLE*/
 SELECT COUNT(*),SAL
 FROM emp
 GROUP BY SAL;
 SELECT JOB,COUNT(*)
 FROM EMP
 GROUP BY JOB;
 /*ORDER BY CLAUSE:
 "IT IS USED SORT THE GIVEN RESULT SET
 IN ASCENDING OR DESCENDING ORDER".
 ->ORDER BY CLAUSE WILL EXECUTE ALWAYS AFTER
 THE SELECT CLAUSE.
 ->BY DEFAULT ORDER BY CLAUSE WILL BE in
   ASCENDING ORDER.
 */
 SELECT SAL
 FROM emp
 ORDER BY SAL DESC;
 SELECT SAL
 FROM emp
 ORDER BY SAL ASC;
 SELECT ENAME
 FROM emp
 ORDER BY ENAME ;